spring:
  datasource:
    url: jdbc:mysql://54.172.113.99:3090/db_admin?serverTimezone=Asia/Shanghai
  redis: # redis配置
    host: 54.172.113.99 # IP

avatarImagesFilePath: /Users/dinglun/Documents/java/java-admin/src/main/resources/static/images/